@rem This file is automatically generated by wasanbon
@rem See http://wasanbon.org
@rem License: Public Domain

@set PATH=%PATH%;%RTM_ROOT%\bin
@start rtcd -f conf/rtc_cpp.conf
timeout 5
@call rtresurrect.bat system/DefaultSystem.xml
@call rtstart.bat system/DefaultSystem.xml