import os, sys, subprocess
import wasanbon
from packageprofile import *


def command(rtcp, commands, verbose = False):
    rtc_dir = os.path.split(rtcp.getRTCProfileFileName())[0]
    if verbose:
        sys.stdout.write("GIT command %s in repository in %s\n" % (repr(commands), rtc_dir))
    pp = PackageProfile(rtcp)
    current_dir = os.getcwd()
    os.chdir(rtc_dir)
    cmd = [wasanbon.setting['local']['git']] + commands
    subprocess.call(cmd)
    os.chdir(current_dir)

def git_init(rtcp, verbose=False):
    command(rtcp, ['init'], verbose=verbose)

    gitignore_files = ['*~', '.pyc', 'build-*']
    fout = open('.gitignore', 'w')
    for filename in gitignore_files:
        fout.write(filename + '\n')
    fout.close()

    command(rtcp, ['add', '.'], verbose=verbose)

    first_comment = 'This if first commit. This repository is generated by wasanbon'    
    commit(rtcp, first_comment, verbose)

    
def commit(rtcp, comment, verbose = False):
    command(rtcp, ['commit', '-a', '-m', comment], verbose=verbose)

def push(rtcp, verbose=False):
    command(rtcp, ['push'], verbose=verbose)

def pull(rtcp, verbose=False):
    command(rtcp, ['pull'], verbose=verbose)
