import os, sys, subprocess
import wasanbon
from packageprofile import *
from rtcprofile import *


def command(rtcp, commands, verbose = False):
    gitenv = os.environ.copy()
    if not 'HOME' in gitenv.keys():
        gitenv['HOME'] = wasanbon.get_home_path()
        print 'Environmental Value HOME (%s) is added.' % gitenv['HOME']

    rtc_dir = os.path.split(rtcp.getRTCProfileFileName())[0]
    if verbose:
        sys.stdout.write(" - GIT command %s in repository in %s\n" % (repr(commands), rtc_dir))
    #pp = PackageProfile(rtcp)
    current_dir = os.getcwd()
    if verbose:
        sys.stdout.write(' - Changing Current Directory to %s\n' % rtc_dir)
    os.chdir(rtc_dir)
    cmd = [wasanbon.setting['local']['git']] + commands
    stdout = None if verbose else subprocess.PIPE
    stderr = None if verbose else subprocess.PIPE

    if verbose:
        sys.stdout.write(' - COMMAND:')
        for c in cmd:
            sys.stdout.write(c + ' ')
        sys.stdout.write('\n')

    subprocess.call(cmd, env=gitenv, stdout=stdout, stderr=stderr)
    os.chdir(current_dir)

def git_init(rtcp, verbose=False):
    command(rtcp, ['init'], verbose=verbose)

    rtc_dir = os.path.split(rtcp.getRTCProfileFileName())[0]
    if verbose:
        sys.stdout.write("GIT command %s in repository in %s\n" % (repr(commands), rtc_dir))
        #pp = PackageProfile(rtcp)
    current_dir = os.getcwd()
    os.chdir(rtc_dir)
    gitignore_files = ['*~', '.pyc', 'build-*']
    fout = open('.gitignore', 'w')
    for filename in gitignore_files:
        fout.write(filename + '\n')
    fout.close()
    os.chdir(current_dir)

    command(rtcp, ['add', '.'], verbose=verbose)

    first_comment = 'This if first commit. This repository is generated by wasanbon'    
    commit(rtcp, first_comment, verbose)

    
def commit(rtcp, comment, verbose = False):
    if verbose:
        print ' - GIT commit changes to my local repository'
    command(rtcp, ['commit', '-a', '-m', comment], verbose=verbose)

def push(rtcp, verbose=False):
    if verbose:
        print ' - GIT push my repository to upstream'
    command(rtcp, ['push'], verbose=verbose)

def pull(rtcp, verbose=False):
    if verbose:
        print ' - GIT pull upstream repository'
    command(rtcp, ['pull'], verbose=verbose)

def checkout(rtcp, hash="", verbose=False):
    if verbose:
        print ' - GIT checkout and overwrite master branch'
    if len(hash)==0:
        command(rtcp, ['checkout', 'master', '--force'], verbose=verbose)
    else:
        command(rtcp, ['checkout', hash], verbose=verbose)

def clone(url, verbose=False):
    if verbose:
        print ' - GIT cloning : %s' % url
    distpath = os.path.join(os.getcwd(), wasanbon.setting['application']['RTC_DIR'], os.path.basename(url))
    if distpath.endswith('.git'):
        distpath = distpath[:-4]
        

    stdout = None if verbose else subprocess.PIPE
    stderr = None if verbose else subprocess.PIPE
    gitenv = os.environ.copy()
    if not 'HOME' in gitenv.keys():
        gitenv['HOME'] = wasanbon.get_home_path()
        print ' - Environment Param HOME (%s) is added.' % gitenv['HOME']

    cmd = [wasanbon.setting['local']['git'], 'clone', url, distpath]
    if verbose:
        sys.stdout.write(' - COMMAND:')
        for c in cmd:
            sys.stdout.write(c + ' ')
        sys.stdout.write('\n')
    subprocess.call(cmd, env=gitenv, stdout=stdout, stderr=stderr)

    curdir = os.getcwd()
    os.chdir(distpath)
    cmd = [wasanbon.setting['local']['git'], 'submodule', 'init']
    if verbose:
        sys.stdout.write(' - COMMAND:')
        for c in cmd:
            sys.stdout.write(c + ' ')
        sys.stdout.write('\n')
    subprocess.call(cmd, env=gitenv, stdout=stdout, stderr=stderr)

    cmd = [wasanbon.setting['local']['git'], 'submodule', 'update']
    if verbose:
        sys.stdout.write(' - COMMAND:')
        for c in cmd:
            sys.stdout.write(c + ' ')
        sys.stdout.write('\n')
    subprocess.call(cmd, env=gitenv, stdout=stdout, stderr=stderr)
    os.chdir(curdir)
    for root, dirs, files in os.walk(distpath):
        if  'RTC.xml' in files:
            return RTCProfile(os.path.join(root, 'RTC.xml'))

    return None
    
def get_hash(rtcp, verbose=False):
    gitenv = os.environ.copy()
    if not 'HOME' in gitenv.keys():
        gitenv['HOME'] = wasanbon.get_home_path()
        print 'Environmental Value HOME (%s) is added.' % gitenv['HOME']

    rtc_dir = os.path.split(rtcp.getRTCProfileFileName())[0]
    if verbose:
        sys.stdout.write(" - GIT command (git log) in repository in %s\n" % rtc_dir)
    pp = PackageProfile(rtcp)
    current_dir = os.getcwd()
    if verbose:
        sys.stdout.write(' - Changing Current Directory to %s\n' % rtc_dir)
    os.chdir(rtc_dir)
    cmd = [wasanbon.setting['local']['git'], 'log', '--pretty=format:"%H"', '-1']
    stdout = subprocess.PIPE
    if verbose:
        sys.stdout.write(' - COMMAND:')
        for c in cmd:
            sys.stdout.write(c + ' ')
        sys.stdout.write('\n')
    p = subprocess.Popen(cmd, env=gitenv, stdout=stdout)
    os.chdir(current_dir)
    
    p.wait()
    
    retval = p.stdout.readline().strip()[1:-1]
    return retval
