import os, sys, subprocess
import wasanbon
from packageprofile import *


def command(rtcp, command, verbose=False):
    rtc_dir = os.path.split(rtcp.getRTCProfileFileName())[0]
    if verbose:
        sys.stdout.write("Mercurial command %s in repository in %s\n" % (repr(command), rtc_dir))
    pp = PackageProfile(rtcp)
    current_dir = os.getcwd()
    os.chdir(rtc_dir)
    cmd = [wasanbon.setting['local']['hg']] + command
    subprocess.call(cmd)
    os.chdir(current_dir)
    
def hg_init(rtcp):
    rtc_dir = os.path.split(rtcp.getRTCProfileFileName())[0]
    sys.stdout.write("Initializing GIT repository in %s\n" % rtc_dir)
    pp = PackageProfile(rtcp)
    current_dir = os.getcwd()
    os.chdir(rtc_dir)
    cmd = [wasanbon.setting['local']['git'], 'init']
    subprocess.call(cmd)

    fout = open('.gitignore', 'w')
    for filename in gitignore_files:
        fout.write(filename + '\n')
    fout.close()

    gitignore_files = ['*~', '.pyc', 'build-*']
    first_commend = 'This if first commit. This repository is generated by wasanbon'

    cmd = [wasanbon.setting['local']['git'], 'add', '.']
    subprocess.call(cmd)
    
    cmd = [wasanbon.setting['local']['git'], 'commit', '-m', first_commend]
    subprocess.call(cmd)
    
    os.chdir(current_dir)

def commit(rtcp, comment, verbose=False):
    command(rtcp, ['commit', '-m', comment], verbose)

def push(rtcp, verbose=False):
    command(rtcp, ['push'], verbose)

def pull(rtcp, verbose=False):
    command(rtcp, ['pull'], verbose)
