import os, sys, subprocess
import wasanbon
from packageprofile import *

gitignore_files = ['*~', '.pyc', 'build-*']
first_commend = 'This if first commit. This repository is generated by wasanbon'

def git_init(rtcp):
    rtc_dir = os.path.split(rtcp.getRTCProfileFileName())[0]
    sys.stdout.write("Initializing GIT repository in %s\n" % rtc_dir)
    pp = PackageProfile(rtcp)
    current_dir = os.getcwd()
    os.chdir(rtc_dir)
    cmd = [wasanbon.setting['local']['git'], 'init']
    subprocess.call(cmd)

    fout = open('.gitignore', 'w')
    for filename in gitignore_files:
        fout.write(filename + '\n')
    fout.close()

    cmd = [wasanbon.setting['local']['git'], 'add', '.']
    subprocess.call(cmd)
    
    cmd = [wasanbon.setting['local']['git'], 'commit', '-m', first_commend]
    subprocess.call(cmd)
    
    os.chdir(current_dir)

def commit(rtcp, comment):
    rtc_dir = os.path.split(rtcp.getRTCProfileFileName())[0]
    sys.stdout.write("Commit Mercurial repository in %s\n" % rtc_dir)
    pp = PackageProfile(rtcp)
    current_dir = os.getcwd()
    os.chdir(rtc_dir)
    cmd = [wasanbon.setting['local']['hg'], 'commit', '-m', comment]
    subprocess.call(cmd)
    os.chdir(current_dir)

def push(rtcp):
    rtc_dir = os.path.split(rtcp.getRTCProfileFileName())[0]
    sys.stdout.write("Push Mercurial repository in %s\n" % rtc_dir)
    pp = PackageProfile(rtcp)
    current_dir = os.getcwd()
    os.chdir(rtc_dir)
    cmd = [wasanbon.setting['local']['hg'], 'push']
    subprocess.call(cmd)
    os.chdir(current_dir)
